version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: gnivc_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gnivc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./config/postgres-data:/var/lib/postgresql/data

#версия кейклока должна соответствовать версии keycloak client на java
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: gnivc_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./config/keycloak/realms/:/opt/keycloak/data/h2/
    ports:
      - "8080:8080"
    command:
      - start-dev
      - --import-realm
      - --features
      - admin-fine-grained-authz

  minio:
    image: minio/minio:latest
    container_name: gnivc_minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin #минимум 3 символа
      MINIO_ROOT_PASSWORD: password #минимум 8 символов
    volumes:
      - ./config/minio:/data

#  rabbitmq:
#    image: 'bitnami/rabbitmq:latest'
#    ports:
#      - '15672:15672'
#      - '5672:5672'

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '29092:29092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: OUTSIDE://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://localhost:29092,INTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8090:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local #устанавливает имя кластера Kafka в "local"
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092 #Устанавливает список адресов загрузки для кластера Kafka
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    links:
      - kafka
      - zookeeper
