spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gnivc_logist_db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: logist-ms
  kafka:
    bootstrap-servers: localhost:29092
    listener:
      # Получение каждой записи должно быть подтверждено
      ack-mode: record

server:
  error:
    include-message: always
  port: 60001
eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
