spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gnivc_logist_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: logist-ms

server:
  error:
    include-message: always
  port: 60001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
