spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/road-constructing-db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: dwh-ms
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/gnivc-road-constructing
server:
  error:
    include-message: always
  port: 60002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

