spring:
  application:
    name: driver-ms
  kafka:
    bootstrap-servers: localhost:29092
server:
  error:
    include-message: always
  port: 60003
eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
minio:
  address: localhost
  port: 9000
  tsl: false
  login: admin
  password: password