spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gnivc
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: portal-ms
  mail:
    host: smtp.mail.ru
    port: 465
    username: timofeev.vadim.developement@mail.ru
    password: WvNc4V8zXhj1ZmvnacXu
    properties:
      mail:
        protocol: smtp
        smtp:
          ssl:
            enable: true

server:
  error:
    include-message: always
  port: 60005
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

keycloak:
  server-url: http://localhost:8080
  realm: gnivc
  resource: admin-cli
  public-client: true
  client-key-password: encK0MQ0xesEwj5Z4RU6da7I3xk3ramD
  admin_username: admin
  admin_password: admin
  user:
    password:
      length: 6
      lower_case_chars_quantity: 4
      upper_case_chars_quantity: 1
      digits_quantity: 1
resetCode:
  length: 16
  lower_case_chars_quantity: 10
  upper_case_chars_quantity: 3
  digits_quantity: 3
  expiration_date_in_minutes: 5

dadata:
  api-endpoint: http://suggestions.dadata.ru/suggestions/api/4_1/rs/findById/party
  api-key: 87923b5a37ad9cf561e9e75e99bc7736caa8899c
  secret: 32151f62e23a70c11568f160e43054af2ce86458